{{- if .Values.registryAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registryAuth | b64enc }}
{{- end }}
