# shellcheck shell=bash
# Deploys the image of the commit to Kubernetes with Helm, to the namespace
# <app>-<environment> of each environment in turn (lib/environments.sh); an
# environment that needs approval waits for it.  Helm waits for a rolling update whose new pods pass their
# readiness probe and rolls back when they do not
# (templates/scripts/deploy-helm.sh).
#
# The cluster is an existing one, given by a kubeconfig file, or a one-node
# k3s cluster in Docker (compose.yml).  The chart is the project's
# (KUBERNETES_CHART) or the generic one in templates/helm/app.

module_secrets() {
  local env key offset
  require_image_module
  ask_server KUBERNETES "Kubernetes cluster" https://k8s.example.com:6443
  if server_external KUBERNETES; then
    ask_local KUBERNETES_KUBECONFIG "Kubeconfig file with access to the cluster" "$HOME/.kube/config"
    for env in $ENVIRONMENTS; do
      ask "KUBERNETES_$(upper "$env")_NODE_PORT" "Node port of $env (empty: a ClusterIP service)" ""
    done
  else
    ask KUBERNETES_API_HOST_PORT "Kubernetes API port on the Docker machine" 6443
    for env in $ENVIRONMENTS; do
      key=$(upper "$env") offset=$(env_offset "$env")
      ask "KUBERNETES_${key}_PORT" "Port of $env on the Docker machine" $((8280 + offset))
      set_value "KUBERNETES_${key}_NODE_PORT" $((30080 + offset))
    done
  fi
  ask KUBERNETES_CHART "Helm chart of the application in the project (empty: the generic chart)" ""
  ask KUBERNETES_REPLICAS "Pods per environment" 2
  ask DEPLOY_HEALTH_PATH "Health check path of the application" /actuator/health
}

# up: the local registry is reached by its service name from the k3s node,
# and kubelet needs a flag on hosts that still use cgroup v1.  The node port
# of each environment is published on the Docker machine (added to
# compose.yml).
module_prepare() {
  local dir env key
  server_external KUBERNETES && return 0
  dir=$(k3s_dir)
  mkdir -p "$dir"
  mkdir -p "$(dirname "$(module_compose_extra "$MODULE_ID")")"
  {
    printf '# Generated by mvn-devops: the port of each environment.\nservices:\n  k3s:\n    ports:\n'
    for env in $ENVIRONMENTS; do
      key=$(upper "$env")
      printf '      - "%s:%s"\n' "$(value "KUBERNETES_${key}_PORT")" "$(value "KUBERNETES_${key}_NODE_PORT")"
    done
  } > "$(module_compose_extra "$MODULE_ID")"
  {
    printf 'mirrors:\n'
    if [[ " $MODULES " == *" image/docker-registry "* ]] && ! server_external REGISTRY; then
      printf '  "localhost:%s":\n    endpoint:\n      - "http://registry:5000"\n' "$(value REGISTRY_HOST_PORT 5000)"
    fi
  } > "$dir/registries.yaml"
  if [[ $(docker info --format '{{.CgroupVersion}}' 2> /dev/null) == 1 ]]; then
    set_value K3S_EXTRA_ARGS '--kubelet-arg=fail-cgroupv1=false'
  else
    set_value K3S_EXTRA_ARGS ''
  fi
}

module_configure() {
  local file helm tries kc
  file="$(k3s_dir)/kubeconfig.yaml"
  if ! server_external KUBERNETES; then
    for (( tries = 0; tries < 90; tries++ )); do
      [[ -s $file ]] && break
      sleep 2
    done
    [[ -s $file ]] || die "k3s did not write its kubeconfig. Check '$DEVOPS_CMD logs k3s'."
  fi
  helm=$(sh "$DEVOPS_HOME/templates/scripts/tool.sh" helm) || die "Could not download Helm"
  kc=$(mktemp)
  kubeconfig host > "$kc"
  for (( tries = 0; tries < 60; tries++ )); do
    KUBECONFIG=$kc "$helm" list --all-namespaces > /dev/null 2>&1 && break
    sleep 2
  done
  if KUBECONFIG=$kc "$helm" list --all-namespaces > /dev/null 2>&1; then
    log_ok "Kubernetes API answers at $(sed -n 's/^ *server: //p' "$kc" | head -n 1)"
    server_external KUBERNETES || ( umask 077; cp "$kc" "$(k3s_dir)/kubeconfig-host.yaml" )
  else
    rm -f "$kc"
    die "The Kubernetes API does not answer with the kubeconfig."
  fi
  rm -f "$kc"
}

module_env() {
  local env
  pipeline_var DEPLOY_NAME "$(image_app_name)"
  pipeline_var DEPLOY_CONTAINER_PORT "$(value IMAGE_PORT 8080)"
  pipeline_var DEPLOY_HEALTH_PATH "$(value DEPLOY_HEALTH_PATH /actuator/health)"
  pipeline_var KUBERNETES_CHART "$(value KUBERNETES_CHART)"
  pipeline_var KUBERNETES_REPLICAS "$(value KUBERNETES_REPLICAS 2)"
  for env in $ENVIRONMENTS; do
    pipeline_var "KUBERNETES_$(upper "$env")_NODE_PORT" "$(value "KUBERNETES_$(upper "$env")_NODE_PORT")"
  done
  pipeline_secret KUBECONFIG_B64 "$(kubeconfig pipeline | base64 | tr -d '\n')"
}

module_stages() {
  local env
  # With Argo CD the pipeline commits to the GitOps branch instead.
  [[ " $MODULES " == *" gitops/"* ]] && return 0
  for env in $ENVIRONMENTS; do
    shell_stage 80 "$env" "deploy-$env" "sh \"\$DEVOPS_SCRIPTS/deploy-helm.sh\" $env"
  done
}

# rollback [environment] [--to TAG]
module_rollback() {
  [[ " $MODULES " == *" gitops/"* ]] && return 0
  local env tag
  rollback_args "$@"
  env=$ROLLBACK_ENV tag=$ROLLBACK_TAG
  log_step "Rollback of $env${tag:+ to $tag}"
  (
    source_pipeline_env
    export KUBECONFIG_B64
    KUBECONFIG_B64=$(kubeconfig host | base64 | tr -d '\n')
    sh "$DEVOPS_HOME/templates/scripts/deploy-helm.sh" "$env" rollback "$tag"
  ) || die "Rollback of $env failed"
  log_ok "$env is rolled back"
}

module_urls() {
  local env
  for env in $ENVIRONMENTS; do
    if server_external KUBERNETES; then
      printf '  %-12s namespace %s-%s%s\n' "${env^}" "$(image_app_name)" "$env" \
        "$(port=$(value "KUBERNETES_$(upper "$env")_NODE_PORT"); [[ -n $port ]] && printf ', node port %s' "$port")"
    else
      printf '  %-12s %s   (rollback: devops.sh rollback %s)\n' "${env^}" \
        "$(host_url "$(value "KUBERNETES_$(upper "$env")_PORT")")" "$env"
    fi
  done
  server_external KUBERNETES || printf '  %-12s export KUBECONFIG=%s/kubeconfig-host.yaml\n' Kubeconfig "$(k3s_dir)"
}
