# shellcheck shell=bash
# Concourse orchestrator.
#
# render  writes generated/concourse/pipeline.yml and vars.yml.  Job "ci" runs
#         the ci stages on every push; job "cd" runs the ci and cd stages and
#         deploys to the environments before the first approval; it is
#         started by hand once ci passed.  Each environment that needs
#         approval has a job of its own, started by hand (the approval) once
#         the job before it passed; it deploys to that environment and the
#         ones after it up to the next approval.
# publish downloads fly from the server and sets the pipeline.  The server is
#         started in Docker, or an existing one (CONCOURSE_SERVER_URL).
# run     triggers a job and watches it:  run [--phase ci|cd|<environment>]

pipeline_name() { printf '%s' "$PROJECT_NAME"; }
concourse_url() { server_url CONCOURSE "$(value CONCOURSE_HOST_PORT 8083)"; }
team() { value CONCOURSE_TEAM main; }
fly_target() { printf 'devops-%s' "$PROJECT_NAME"; }

module_secrets() {
  ask_server CONCOURSE Concourse https://ci.example.com
  if server_external CONCOURSE; then
    ask CONCOURSE_TEAM "Concourse team" main
    ask_local CONCOURSE_USER "Concourse user (local user of the team)" admin
    ask_secret CONCOURSE_PASSWORD "Password of $(value CONCOURSE_USER)"
    ask MAVEN_IMAGE "Docker image for build tasks" "$(maven_image)"
    return
  fi
  ask CONCOURSE_HOST_PORT "Concourse port on the Docker machine" 8083
  ask CONCOURSE_USER "Concourse user" admin
  ask_secret CONCOURSE_PASSWORD "Concourse password" "$(random_password)"
  ask_secret CONCOURSE_DB_PASSWORD "Concourse database password" "$(random_password)"
  ask_secret CONCOURSE_CLIENT_SECRET "Concourse web client secret" "$(random_password)"
  ask_secret CONCOURSE_TSA_CLIENT_SECRET "Concourse TSA client secret" "$(random_password)"
  ask MAVEN_IMAGE "Docker image for build tasks" "$(maven_image)"
}


yaml_quote() { local v=${1//\'/\'\'}; printf "'%s'" "$v"; }

# render_job <ci|cd|environment> [previous job]: the ci job runs ci stages,
# the cd job ci, cd and the stages of the environments before the first
# approval, an environment's job the stages behind its approval, for the
# commit the previous job deployed.
render_job() {
  local job=$1 previous=${2:-} flags phase name args key image group
  flags="$(maven_flags "" "$CI_SETTINGS") -Dmaven.repo.local=../.m2/repository"
  image=$(value MAVEN_IMAGE "$(maven_image)")

  printf '  - name: %s\n    plan:\n      - get: source\n' "$job"
  case $job in
    ci) printf '        trigger: true\n' ;;
    cd) printf '        passed: [ci]\n' ;;
    *) printf '        passed: [%s]\n' "$previous" ;;
  esac
  printf '      - task: %s\n        config:\n          platform: linux\n' "$job"
  printf '          image_resource:\n            type: registry-image\n            source:\n'
  printf '              repository: %s\n              tag: %s\n' "${image%:*}" "$(yaml_quote "${image##*:}")"
  printf '          inputs:\n            - name: source\n'
  printf '          caches:\n            - path: .m2\n            - path: .tools\n'
  printf '          params:\n'
  while IFS= read -r key; do
    printf '            %s: ((%s))\n' "$key" "$key"
  done < "$DEVOPS_ENV/pipeline.keys"
  printf '          run:\n            dir: source\n            path: sh\n            args:\n              - -ec\n              - |\n'
  printf '                export DEVOPS_TOOLS="$PWD/../.tools"\n'
  printf '                { command -v git && command -v ssh && command -v curl; } > /dev/null || { apt-get update -qq && apt-get install -y -qq git openssh-client curl > /dev/null; }\n'
  printf '                %s\n' "$(pipeline_ci_setup)"
  while IFS='|' read -r _ phase name args; do
    group=$(phase_group "$phase")
    case $job:$group in
      ci:ci | cd:ci | cd:cd) ;;
      *) [[ $group == "$job" ]] || continue ;;
    esac
    printf '                echo "==> %s"\n                %s\n' "$name" "$(stage_command "$flags" "$args")"
  done < <(pipeline_stages)
}

module_render() {
  local dir="$DEVOPS_GENERATED/concourse" line key previous gate
  mkdir -p "$dir"
  {
    printf '# Generated by mvn-devops. Re-create with: devops.sh render\n'
    printf 'resources:\n  - name: source\n    type: git\n    icon: github\n    source:\n'
    printf '      uri: ((GITHUB_URL))/((GITHUB_REPOSITORY)).git\n'
    printf '      branch: ((GIT_BRANCH))\n'
    printf '      username: ((GITHUB_USERNAME))\n'
    printf '      password: ((GITHUB_TOKEN))\n\n'
    printf 'jobs:\n'
    render_job ci
    render_job cd
    previous='cd'
    for gate in $(pipeline_gates); do
      render_job "$gate" "$previous"
      previous=$gate
    done
  } > "$dir/pipeline.yml"

  ( umask 077
    while IFS= read -r line; do
      key=${line%%=*}
      printf '%s: %s\n' "$key" "$(yaml_quote "${line#*=}")"
    done < "$DEVOPS_ENV/pipeline.env" > "$dir/vars.yml"
  )
  log_ok "Wrote $dir/pipeline.yml"
  log_ok "Wrote $dir/vars.yml"
}

fly_bin() {
  local bin="$DEVOPS_STATE/bin/fly" platform arch
  case $(uname -s) in
    Linux*) platform=linux ;;
    Darwin*) platform=darwin ;;
    MINGW*|MSYS*|CYGWIN*) platform=windows; bin+=.exe ;;
    *) die "Unsupported platform $(uname -s)" ;;
  esac
  case $(uname -m) in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) die "Unsupported architecture $(uname -m)" ;;
  esac
  if [[ ! -x $bin ]]; then
    mkdir -p "$(dirname "$bin")"
    curl -sfL "$(concourse_url)/api/v1/cli?arch=$arch&platform=$platform" -o "$bin" \
      || die "Could not download fly from $(concourse_url)"
    chmod +x "$bin"
  fi
  printf '%s' "$bin"
}

fly() {
  "$(fly_bin)" --target "$(fly_target)" "$@"
}

module_configure() {
  wait_http "$(concourse_url)/api/v1/info" 300 '^200$' || die "Concourse at $(concourse_url) is not up. Check '$DEVOPS_CMD logs concourse' or the server."
  fly login --concourse-url "$(concourse_url)" --team-name "$(team)" \
    --username "$(value CONCOURSE_USER admin)" --password "$(require_value CONCOURSE_PASSWORD)" > /dev/null
  log_ok "Logged in to $(concourse_url) (team $(team))"
}

module_publish() {
  local dir="$DEVOPS_GENERATED/concourse"
  fly set-pipeline --non-interactive --pipeline "$(pipeline_name)" \
    --config "$dir/pipeline.yml" --load-vars-from "$dir/vars.yml"
  fly unpause-pipeline --pipeline "$(pipeline_name)"
  log_ok "Pipeline '$(pipeline_name)' is set at $(concourse_url)/teams/$(team)/pipelines/$(pipeline_name)"
}

module_run() {
  local job=ci
  while (( $# )); do
    case $1 in
      --phase) job=$2; shift 2 ;;
      *) die "run: unknown option $1 (use --phase ci|cd|<environment>)" ;;
    esac
  done
  if [[ $job != ci && $job != cd ]]; then
    job=$(env_resolve "$job") || die "--phase must be ci, cd or an environment ($(environments))"
    [[ $(phase_group "$job") == "$job" ]] \
      || die "$job needs no approval: it is deployed by the job $(phase_group "$job")"
  fi
  fly status > /dev/null 2>&1 || module_configure
  # Build the latest commit, not the one Concourse saw at its last check.
  # Right after setup the worker may not have registered yet.
  if [[ $job == ci ]]; then
    local tries
    for (( tries = 0; tries < 30; tries++ )); do
      fly check-resource --resource "$(pipeline_name)/source" > /dev/null 2>&1 && break
      sleep 2
    done
  fi
  fly trigger-job --job "$(pipeline_name)/$job" --watch
}

module_urls() {
  printf '  %-12s %s   (%s / devops.sh get CONCOURSE_PASSWORD)\n' Concourse "$(concourse_url)" "$(value CONCOURSE_USER admin)"
}
