# shellcheck shell=bash
# Local orchestrator: runs every stage with mvn on this machine.
# The tools still run in containers, on this machine or on the one DOCKER_HOST
# points to, and are reached through DEVOPS_HOST.
#
# "run" runs ci, cd and the environments before the first one that needs
# approval.  "run --phase <environment>" is the approval: it runs that
# environment and the ones after it up to the next approval.  "--phase ci"
# runs only ci, "--phase cd" what follows ci up to the first approval.

# Writes a standalone script, handy for IDE run configurations.  The stages
# behind an approval run only with "pipeline.sh --approve <environment>".
module_render() {
  local out="$DEVOPS_GENERATED/pipeline.sh" phase name args flags group
  flags=$(maven_flags "$PROJECT_DIR" "$(printf '%q' "$DEVOPS_HOME/templates/settings.xml")")
  {
    printf '#!/usr/bin/env bash\n# Generated by mvn-devops. Re-create with: devops.sh render\nset -euo pipefail\n'
    printf '# Usage: pipeline.sh                      ci, cd and the environments before the first approval\n'
    printf '#        pipeline.sh --approve <env>      the stages that wait for the approval of <env>\n'
    printf 'approve=cd\n[[ ${1:-} == --approve ]] && approve=${2:?--approve needs an environment}\n'
    printf '[[ ${1:-} == --prod ]] && approve=%q\n' "$(env_last)"
    printf 'source %q\n' "$DEVOPS_ENV/pipeline.sh"
    printf 'cd %q\n' "$PROJECT_DIR"
    while IFS="|" read -r _ phase name args; do
      group=$(phase_group "$phase")
      [[ $group == ci ]] && group='cd'
      printf '\nif [[ $approve == %s ]]; then\n  echo "==> [%s] %s"\n  %s\nfi\n' \
        "$group" "$phase" "$name" "$(stage_command "$flags" "$args")"
    done < <(pipeline_stages)
  } > "$out"
  chmod 700 "$out"
  log_ok "Wrote $out"
}

module_run() {
  local dry=0 from="" only="" phase="" phase_name name args flags line
  while (( $# )); do
    case $1 in
      --dry-run) dry=1; shift ;;
      --from) from=$2; shift 2 ;;
      --only) only=$2; shift 2 ;;
      --phase) phase=$2; shift 2 ;;
      *) die "run: unknown option $1 (use --dry-run, --from <stage>, --only <stage>, --phase ci|cd|<environment>)" ;;
    esac
  done
  phase=$(pipeline_phase "$phase")
  flags=$(maven_flags "$PROJECT_DIR" "$(printf '%q' "$DEVOPS_HOME/templates/settings.xml")")
  command -v mvn > /dev/null || (( dry )) || die "mvn is not installed"

  pipeline_select "$phase" "$from" "$only"
  for line in "${SELECTED[@]}"; do
    IFS="|" read -r phase_name name args <<< "$line"
    log_step "[$phase_name] $name"
    log_dim "$(stage_command "$flags" "$args")"
    (( dry )) && continue
    # shellcheck disable=SC1091
    ( source "$DEVOPS_ENV/pipeline.sh"; cd "$PROJECT_DIR"; eval "$(stage_command "$flags" "$args")" ) \
      || die "Stage '$name' failed. Resume with '$DEVOPS_CMD run --from $name'."
  done
  log_ok "Pipeline finished"
  [[ -n $only ]] || pipeline_next "$phase"
  return 0
}
