config:
  tracing:
    otlpEndpoint: http://localhost:4317
    randomSampling: true
    fields:
      add:
        gen_ai.agent.id: request.headers["x-nexusphere-agent"]
        nexusphere.principal.id: request.headers["x-nexusphere-principal"]
binds:
- port: 3000
  listeners:
  - routes:
    - backends:
      - mcp:
          targets:
          - name: demo
            mcp:
              host: http://localhost:8091/mcp
