package com.nexusphere.shared.error;

public enum ErrorCategory {
    VALIDATION_ERROR,
    AUTHENTICATION_ERROR,
    AUTHORIZATION_ERROR,
    NOT_FOUND,
    CONFLICT,
    BUSINESS_RULE_VIOLATION,
    FEDERATION_ERROR,
    DELEGATION_ERROR,
    AGREEMENT_ERROR,
    TRANSACTION_ERROR,
    RATE_LIMIT_EXCEEDED,
    INFRASTRUCTURE_ERROR
}
