# shellcheck shell=bash
# Maven in a container: each run starts a container from the official Maven
# image on the Docker machine (this one, or another one that DOCKER_HOST
# points to), checks the commit out of GitHub and runs the stages with mvn in
# it.  Nothing of this machine is used but Docker: no Java, no Maven, no
# checkout.  The container joins the network of the tools and reaches them by
# their names, as Jenkins and Concourse do.  A volume keeps the Maven
# repository and the downloaded tools between runs.
#
# "run" checks out the head of GIT_BRANCH and runs ci, cd and the
# environments before the first approval.  "run --phase <environment>" is the
# approval: it deploys the commit that passed the part of the pipeline before
# it.  "--phase ci" runs only ci, "--phase cd" what follows ci up to the
# first approval.

runner_name() { printf '%s-runner' "$(compose_project)"; }
runner_volume() { printf '%s-runner' "$(compose_project)"; }
runner_script() { printf '%s/maven-container/run.sh' "$DEVOPS_GENERATED"; }
runner_image() { value MAVEN_IMAGE "$(maven_image)"; }

module_secrets() {
  ask MAVEN_IMAGE "Docker image the stages run in" "$(maven_image)"
}

# Writes the script the container runs.  DEVOPS_STAGES names the stages to
# run; DEVOPS_AFTER, when set, the part of the pipeline whose commit to check
# out; DEVOPS_PASSES the part this run completes, recorded in the volume.
module_render() {
  local out flags phase name args
  out=$(runner_script)
  mkdir -p "$(dirname "$out")"
  flags="$(maven_flags "" "$CI_SETTINGS") -Dmaven.repo.local=/cache/m2"
  {
    printf '# Generated by mvn-devops. Re-create with: devops.sh render\n'
    printf '# Runs in the container of each "devops.sh run" (bash -s).\n'
    cat <<'SCRIPT'
set -e
export DEVOPS_TOOLS=/cache/tools
{ command -v git && command -v ssh && command -v curl; } > /dev/null || { apt-get update -qq && apt-get install -y -qq git openssh-client curl > /dev/null; }
mkdir -p /cache/passed
commit=''
if [ -n "${DEVOPS_AFTER:-}" ]; then
  [ -f "/cache/passed/$DEVOPS_AFTER" ] || { echo "No commit has passed $DEVOPS_AFTER yet; run that part of the pipeline first." >&2; exit 1; }
  commit=$(cat "/cache/passed/$DEVOPS_AFTER")
fi
git config --global credential.helper '!f() { echo "username=$GITHUB_USERNAME"; echo "password=$GITHUB_TOKEN"; }; f'
git clone -q --branch "$GIT_BRANCH" "$GITHUB_URL/$GITHUB_REPOSITORY.git" /work/source
cd /work/source
[ -z "$commit" ] || git checkout -q "$commit"
echo "==> commit $(git rev-parse --short=12 HEAD) of $GITHUB_REPOSITORY"
want() { case " $DEVOPS_STAGES " in *" $1 "*) return 0 ;; esac; return 1; }
failed() { echo "Stage '$1' failed." >&2; exit 1; }
SCRIPT
    printf '%s\n' "$(pipeline_ci_setup)"
    while IFS='|' read -r _ phase name args; do
      printf 'if want %s; then\n  echo "==> [%s] %s"\n  bash -ec %q || failed %s\nfi\n' \
        "$name" "$phase" "$name" "$(stage_command "$flags" "$args")" "$name"
    done < <(pipeline_stages)
    printf '%s\n' '[ -z "${DEVOPS_PASSES:-}" ] || git rev-parse HEAD > "/cache/passed/$DEVOPS_PASSES"'
  } > "$out"
  log_ok "Wrote $out"
}

module_publish() {
  docker pull -q "$(runner_image)" > /dev/null || die "Could not pull $(runner_image)"
  log_ok "The stages run in $(runner_image) on the Docker machine ($(docker_host_default))"
}

module_run() {
  local dry=0 from="" only="" phase="" group="" after="" passes="" gate line name names=""
  local -a network=()
  while (( $# )); do
    case $1 in
      --dry-run) dry=1; shift ;;
      --from) from=$2; shift 2 ;;
      --only) only=$2; shift 2 ;;
      --phase) phase=$2; shift 2 ;;
      *) die "run: unknown option $1 (use --dry-run, --from <stage>, --only <stage>, --phase ci|cd|<environment>)" ;;
    esac
  done
  phase=$(pipeline_phase "$phase")
  pipeline_select "$phase" "$from" "$only"
  for line in "${SELECTED[@]}"; do
    name=${line#*|}; name=${name%%|*}
    names+=" $name"
  done

  # An approval deploys the commit that passed the part before it.
  if [[ -z $only ]]; then
    case $phase in
      ci) ;;
      ''|cd) passes='cd' ;;
      *)
        group=$(phase_group "$phase")
        passes=$group
        after='cd'
        for gate in $(pipeline_gates); do
          [[ $gate == "$group" ]] && break
          after=$gate
        done ;;
    esac
  fi

  if (( dry )); then
    log_info "Stages in $(runner_image):${names}"
    [[ -n $only ]] || pipeline_next "$phase"
    return 0
  fi
  command -v docker > /dev/null || die "docker is not installed"
  if [[ -z $after ]] && git -C "$PROJECT_DIR" rev-parse '@{u}' > /dev/null 2>&1 \
      && [[ $(git -C "$PROJECT_DIR" rev-list --count '@{u}..HEAD') != 0 ]]; then
    log_warn "Some commits are not pushed; the container builds what is on $(value GIT_BRANCH main) in GitHub."
  fi
  module_render > /dev/null
  docker network inspect "$(compose_project)_default" > /dev/null 2>&1 \
    && network=(--network "$(compose_project)_default")
  log_step "Running${names} in $(runner_image)"
  docker run --rm -i --name "$(runner_name)" "${network[@]}" \
    --env-file "$(native_path "$DEVOPS_ENV/pipeline.env")" \
    -e DEVOPS_STAGES="${names# }" -e DEVOPS_AFTER="$after" -e DEVOPS_PASSES="$passes" \
    -v "$(runner_volume):/cache" "$(runner_image)" bash -s < "$(runner_script)" \
    || die "The pipeline failed. Resume with '$DEVOPS_CMD run --from <stage>'."
  log_ok "Pipeline finished"
  [[ -n $only ]] || pipeline_next "$phase"
  return 0
}

module_destroy() {
  docker volume rm -f "$(runner_volume)" > /dev/null 2>&1 || true
}
