# shellcheck shell=bash
# Docker compose wrapper and readiness checks.

# Docker on Windows does not understand Git Bash paths (/c/Users/..., /tmp/...),
# so paths written into compose files and their .env are native ones.
native_path() {
  if command -v cygpath > /dev/null; then cygpath -m "$1"; else printf '%s' "$1"; fi
}

compose_project() {
  printf 'devops-%s' "$(printf '%s' "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-\n' '-')"
}

# compose <docker compose args...>
compose() {
  local -a files=()
  local file
  while IFS= read -r file; do
    [[ -n $file ]] && files+=(-f "$file")
  done < <(compose_files)
  if (( ${#files[@]} == 0 )); then
    log_dim "No selected module needs containers."
    return 0
  fi
  command -v docker > /dev/null || die "docker is not installed"
  docker compose --project-name "$(compose_project)" \
    --project-directory "$DEVOPS_STATE" \
    --env-file "$DEVOPS_ENV/compose.env" \
    "${files[@]}" "$@"
}

# compose_export [dir]: one standalone docker-compose.yml with the selected
# tools, plus the .env it reads, so the developer can use plain docker compose.
# Paths are written out; every other ${VAR} stays and is read from .env.
compose_export() {
  local dir=${1:-$DEVOPS_STATE/compose} file tmp var copy content
  local -a files=()
  [[ -n $(compose_files) ]] || { log_dim "No selected module needs containers."; return 0; }
  command -v docker > /dev/null || die "docker is not installed"
  mkdir -p "$dir"
  dir=$(cd "$dir" && pwd)
  tmp=$(mktemp -d)
  while IFS= read -r file; do
    copy="$tmp/$(printf '%s' "${file#"$DEVOPS_MODULES_DIR"/}" | tr / -)"
    content=$(< "$file")
    for var in DEVOPS_HOME DEVOPS_STATE PROJECT_DIR; do
      content=${content//"\${$var}"/$(native_path "${!var}")}
    done
    content=${content//'${PROJECT_NAME}'/$PROJECT_NAME}
    printf '%s\n' "$content" > "$copy"
    files+=(-f "$copy")
  done < <(compose_files)
  if ! docker compose --project-name "$(compose_project)" --project-directory "$DEVOPS_STATE" \
      --env-file "$DEVOPS_ENV/compose.env" "${files[@]}" config --no-interpolate > "$tmp/merged.yml"; then
    rm -rf "$tmp"
    die "docker compose could not merge the compose files"
  fi
  {
    printf '# Generated by mvn-devops for %s: %s\n' "$PROJECT_NAME" "${MODULES//$'\n'/ }"
    printf '# Re-create with: devops.sh export-compose.  ${VARS} are read from .env next to this file.\n'
    cat "$tmp/merged.yml"
  } > "$dir/docker-compose.yml"
  rm -rf "$tmp"
  ( umask 077; cp "$DEVOPS_ENV/compose.env" "$dir/.env" )
  # The .env holds passwords; keep it out of git when written into the project.
  if [[ $dir != "$DEVOPS_STATE"* ]] && ! grep -qx '.env' "$dir/.gitignore" 2>/dev/null; then
    printf '.env\n' >> "$dir/.gitignore"
  fi
  log_ok "Wrote $dir/docker-compose.yml and $dir/.env"
}

# wait_http <url> [timeout seconds] [accepted status regex]
wait_http() {
  local url=$1 timeout=${2:-300} accept=${3:-'^(200|401|403)$'} start code
  start=$(date +%s)
  printf '  waiting for %s ' "$url"
  while true; do
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "$url" || true)
    if [[ $code =~ $accept ]]; then
      printf ' up\n'
      return 0
    fi
    if (( $(date +%s) - start > timeout )); then
      printf ' timeout\n'
      return 1
    fi
    printf '.'
    sleep 5
  done
}
